config/routes.rb
Rails.application.routes.draw do

  resources :tasks
  root 'dashboard#index'

  get 'deploy/:id', to: 'jobs#deploy', as: :deploy

  resources :jobs
  resources :projects
  resources :dashboard

end

app/models/job.rb
class Job < ActiveRecord::Base

  belongs_to :task

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks
  has_many :jobs, -> {order "created_at DESC"}, through: :tasks

  def default_task
    # if default_task_id = nil assign variable task_id to the first task associated to project
    # otherwise assign task_id to the default_task_id
    
    default_task_id.nil? ? tasks.first : default_task_id

    # if @project.default_task_id.nil? 
    #   task_id = @project.tasks.first
    # else
    #   task_id = @project.default_task_id
    # end
  end

  def friendly_id
    title.downcase.gsub(/\W+/, '-')
  end

  def has_tasks
    # if the project has tasks, return a not empty, if no tasks, return empty
    !tasks.empty?
  end

  def self.options_list
    Project.all.to_a.map! {|project| [project.title, project.id] }
  end

  def repo_exists
    @repo = friendly_id
    @repo_dir = Rails.root.join("tmp/repos/#{@repo}")
    
    if Dir.exist? @repo_dir
      system %{cd #{@repo_dir}; git pull}
    else
      system %{mkdir -p #{@repo_dir}; cd #{@repo_dir}; git clone -b #{branch} #{repo} . }
    end

    @repo_dir
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  has_many :jobs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @projects = Project.all
  end
end

app/controllers/jobs_controller.rb
require 'open3'

class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  def run
    @repo_dir = @job.task.project.repo_exists

    Open3.popen3(@job.task.command, :chdir=>@repo_dir) {|i,o,e,t|
      @job.log =  o.read 
    }


  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    run

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /deploy/1
  def deploy
    @project = Project.find(params[:id])
    logger.info ""
    logger.info "run deploy script"
    logger.info @project.inspect
    logger.info @project.id
    logger.info ""
    render 'projects/show'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:task_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @jobs = Job.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :repo, :branch)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :command, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboard/index.html.erb
<p id="notice"><%= notice %></p>

<table class="pure-table pure-table-horizontal pure-table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td>
          <h2><%= link_to project.title, project %></h2>
          <p><%= project.description %></p>
        </td>
        <td><%= link_to 'Deploy', deploy_path(project), class: 'pure-button button-success button-xlarge' if project.has_tasks %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table class="pure-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Command</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.description %></td>
        <td><%= job.command %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.task.description %>
</p>

<p>
  <strong>Command:</strong>
  <span class="command"><%= @job.task.command %></span>
</p>


<p>
  <strong>Log:</strong>
  <pre class="job-log"><%= @job.log %></pre>
</p>

<%= link_to 'Back', :back %>

app/views/layouts/_menu.html.erb
    <div id="menu">
        <div class="pure-menu">
            <%= link_to "bqpd", root_url, class: "pure-menu-heading" %>

            <ul class="pure-menu-list">
                <li class="pure-menu-item"><%= link_to 'Dashboard', root_url, class: 'pure-menu-link' %></li>
                <li class="pure-menu-item"><%= link_to 'Projects Admin', projects_path, class: 'pure-menu-link' %></li>
                <li class="pure-menu-item"><%= link_to 'Tasks Admin', tasks_path, class: 'pure-menu-link' %></li>
            </ul>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bqpd</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
  <div id="layout">
    <!-- Menu toggle -->
    <a href="#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
    </a>

    <%= render "layouts/menu" %>

    <div id="main">
        <div class="header">
            <h1>Projects Dashboard</h1>
            <h2>View projects and their status here</h2>
        </div>

        <div class="content">


            <%= yield %>


        </div>
    </div>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, html: {class: "pure-form pure-form-aligned"}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <div class="pure-control-group form-field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="pure-control-group form-field">
    <%= f.label :description %>
    <%= f.text_field :description, size: 50 %>
  </div>

  <div class="pure-control-group form-field">
    <%= f.label :repo %>
    <%= f.text_field :repo %>
  </div>


  <div class="pure-control-group form-field">
    <%= f.label :branch %>
    <%= f.text_field :branch, {value: "master"} %>
  </div>
  <div class="pure-controls actions">
    <%= f.submit 'Update', class: 'pure-button button-xlarge button-success' %>
  </div>
  </fieldset>
<% end %>

app/views/projects/edit.html.erb
<h1 class="center">Editing Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Projects</h1>

<div class="project-new"><p><%= link_to 'New Project', new_project_path, class: "pure-button button-secondary button-small" %></p></div>

<table class="pure-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th class="button-small">Edit</th>
      <th class="button-xsmall">Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.title, project %></td>
        <td><%= project.description %></td>
        <td><%= link_to '', edit_project_path(project), class: "fa fa-pencil-square-o" %></td>
        <td><%= link_to '', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-times" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<h1 class="center">New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

[ <%= link_to 'Projects List', projects_path %> ]

<div class="project-title">
  <ul class="project-menu">
    <li><%= link_to '', edit_project_path(@project), class: 'fa fa-pencil-square-o' %> </li>
    <li><%= link_to '', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-times" %></li>
  </ul>
  <h1><%= @project.title %></h1>
  <p>Description: <%= @project.description %> </p>
  <p>Repository: <%= @project.repo %> </p>
  <p>Branch: <%= @project.branch %> </p>
</div>


<% if @project.tasks.exists? %>
  <table class="pure-table pure-table-horizontal pure-table-striped">
    <thead>
      <tr>
        <th colspan="2"><h2>Available Tasks</h2><%= link_to 'New Task', new_task_path, class: "new-task pure-button button-secondary button-small" %></th>
  
      </tr>
    </thead>

    <tbody>
      <% @project.tasks.each do | task | %>
        <tr>
          <td>
            <h3><%= link_to task.title, edit_task_path(task) %></h3>
            <p><%= task.description %></p>
          </td>

          <td>
            <%= button_to "RUN", { controller: "jobs", action: "create" }, params: {"job[task_id]" => task.id }, form_class: 'pure-button button-success run-button' %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <%= link_to 'Create a New Task', new_task_path, class: "pure-button button-secondary button-small" %>
<% end %>


<% if @project.jobs.exists? %>
  <h3>Completed Jobs</h3>
  <dl class="completed-jobs">
  <% @project.jobs.each do | job | %>
    <dt><%= link_to job.task.title , job %> (<%= job.created_at %>)</dt>
      <dd><code class="command"><%= job.task.command %></code></dd>
  <% end %>
  </dl>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for(@task, html: {class: "pure-form pure-form-aligned"}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <div class="pure-control-group form-field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="pure-control-group form-field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="pure-control-group form-field">
    <%= f.label :command %>
    <%= f.text_field :command %>
  </div>

  <div class="pure-controls form-field">
    <%= f.label :project %>
    <p>Select the project this task belongs to</p>
    <%= f.select(:project_id, Project.options_list) %>
  </div>

  <div class="pure-controls actions">
    <p><%= f.submit 'Submit', class: 'pure-button button-xlarge button-success' %></p>
  </div>
  </fieldset>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="center">Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table class="pure-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.project.title %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1 class="center">New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Command:</strong>
  <%= @task.command %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project.title %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Tasks list', tasks_path %>